#ifndef CONFIG_USER_H
#define CONFIG_USER_H

#include "../../config.h"

#define RGB_DI_PIN B5
#define RGBLIGHT_ANIMATIONS

#undef RGBLED_NUM
#define RGBLED_NUM 12
#define RGBLIGHT_HUE_STEP 8
#define RGBLIGHT_SAT_STEP 8
#define RGBLIGHT_VAL_STEP 8
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL

#endif
